mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import routers
from feeds.api import ArticlesViewSets
from mainApp.api import BrandViewSets, CarViewSets

router = routers.DefaultRouter()
router.register('api/feed', ArticlesViewSets, 'feeds')
router.register('api/car_list', CarViewSets, 'cars')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('feeds/', include('feeds.urls'))
]

if settings.DEBUG:
    urlpatterns += router.urls
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


mysite/news/urls.py
from news.views import *
from django.urls import path

app_name = 'news'

urlpatterns = [
    path('', post_list, name='post_list'),
    path('create/', post_create, name='post_create'),
    path('delete/<int:id>/', post_delete, name='post_delete'),
    path('detail/<int:id>/', post_detail, name='post_detail'),
    path('update/<int:id>/', post_update, name='post_update')
]



mysite/news/forms.py
from django import forms
from news.models import Articles


class ArticlesForm(forms.ModelForm):
    class Meta:
        model = Articles
        fields = [
            'title',
            'post',
            'image',
            'user',
        ]

mysite/news/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.utils import timezone
from news.models import Articles
from news.forms import ArticlesForm
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


def post_list(request):
    posts = Articles.objects.all()
    user = Articles.user
    paginator = Paginator(posts, 3)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    context = {
        'title': 'News list',
        'object_list': posts,
        'page_request_var': page_request_var,
        'user': user,

    }
    return render(request, 'news/post_list.html', context)


def post_create(request):
    form = ArticlesForm(request.POST or None, request.FILES or None)
    if not request.user.is_staff:
        raise render(request, '404.html', status=404)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Post created!!!")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'title': 'Post create',
        'form': form
    }
    return render(request, 'news/post_create.html', context)


def post_update(request, id):
    instance = get_object_or_404(Articles, id=id)
    form = ArticlesForm(request.POST or None,
                        request.FILES or None,
                        instance=instance)
    if not request.user.is_staff:
        raise render(request, '404.html', status=404)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "<a href = '#'>Post updated!!!</a> ", extra_tags='safe_html')
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'title': 'Post update',
        'form': form
    }

    return render(request, 'news/post_create.html', context)


def post_delete(request, id):
    instance = get_object_or_404(Articles, id=id)
    instance.delete()
    messages.success(request, "Post deleted!!!")
    if not request.user.is_staff:
        raise render(request, '404.html', status=404)
    return redirect('news:post_list')


def post_detail(request, id):
    instance = get_object_or_404(Articles, id=id)
    context = {
        'title': 'Post detail',
        'object': instance
    }
    if not request.user.is_staff:
        raise render(request, '404.html', status=404)
    return render(request, 'news/post_detail.html', context)

mysite/news/templates/news/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}SVOE AVTO{% endblock head_title%}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/post.css' %}">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" type="text/css">
    <style>
        {% block style %}
        {% endblock style %}
    </style>
</head>
<body>
    <div class="page-header">
        <a href="/news/create/" class="top-menu"><span class="glyphicon glyphicon-plus"></span>Add post</a>
        <a href="/"><h1>Main</h1></a>
    </div>
    {% include 'news/message_display.html' %}
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}

                {% endblock %}
            </div>
        </div>
        <footer class="footer">
            <div class="container">
                <p>@Copyright 2022 Group Python Dev(9.08)</p>
            </div>
        </footer>
    </div>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</body>

</html>

mysite/news/templates/news/post_create.html
{% extends 'news/base.html' %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3"><br>
        <form action="" method="POST" enctype="multipart/form-data">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Create post!">
        </form>
    </div>
{% endblock %}

mysite/news/templates/news/post_detail.html
{% extends 'news/base.html' %}

{% block head_title %}{{ object.title }}{% endblock head_title %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3"><br>
        {% if object.image %}
            <img src="{{ object.image.url }}" class="img-responsive">
        {% endif %}
        <h1>{{ object.title }}</h1>
        <small>{{ object.timestamp }}</small>
        <p>{{ object.post|linebreaks }}</p>
    </div>
{% endblock %}

mysite/news/templates/news/post_list.html
{% extends 'news/base.html' %}


{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        <h1>{{ title }}</h1>
        {% for post in object_list %}
            <div class="row">
                <div class="col-cm-12">
                    <div class="thumbnail">
                        {% if post.image %}
                            <img src="{{ post.image.url }}" class="img-responsive">
                        {% endif %}
                        <div class="caption">
                            <h3><a href="{{post.get_absolute_url }}">{{ post.title }}</a></h3>
                            <h5>{{ post.user }}</h5>
                            <p>{{ post.content|linebreaks|truncatechars:50 }}</p>
                            <p>published: {{ post.timestamp|timesince }} тому</p>
                            <a href="{{ post.get_absolute_url}}" class = "btn btn-warning" role="button">View</a>
                            <a href="{% url 'news:post_update' post.id %}" class = "btn btn-warning" role="button">Update</a>
                            <a href="{% url 'news:post_delete' post.id %}" class = "btn btn-danger" role="button">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    <div class="paginator">
        <span class="step-link">
            {% if object_list.has_previous %}
                <a href = "?{{ page_request_var }}={{ object_list.previous_page_number }}">Previous</a>
            {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}
        </span>
            {% if object_list.has_next %}
                <a href = "?{{ page_request_var }}={{ object_list.next_page_number}}">Next</a>
            {% endif %}
        </span>
    </div><br>
    </div>
{% endblock %}